[package]
name = "electrical_grid_model"
version = "0.1.0"
edition = "2021"

# Path to the build script
build = "build.rs"

[dependencies]

# Define un lib dummy
[lib]
name = "electrical_grid_model"
path = "src/lib.rs"