name: Rust Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
          target: x86_64-unknown-linux-gnu

      - name: Build the project
        run: cargo build --release

      - name: Create ZIP of artifacts
        run: |
          mkdir -p release_artifacts
          cp -r target/release/assets release_artifacts/
          cp target/release/electrical_grid_cli release_artifacts/
          zip -r release_artifacts.zip release_artifacts

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-artifacts
          path: release_artifacts.zip