[package]
name = "electrical_grid_core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
prost = "0.13.3"
candle-core = { version = "0.7.2", features = [ "metal" ] }
candle-onnx = "0.7.2"
chrono = "0.4.38"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
quick-xml = { version = "0.36.2", features = ["serialize"] }
