[package]
name = "electrical_grid_core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
electrical_grid_model = { path = "../electrical_grid_model" }

chrono = "0.4.38"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
quick-xml = { version = "0.36.2", features = ["serialize"] }
tract-onnx = "0.21.7"